### ISSUE TITLE
Restarting the Server doesn't pick up changes to db.json

### ISSUE THREAD

**Issue by kpmccaffrey** [R35007/mock-server-vscode-extension#1]
When I make changes to db.json I can see the server restart but it doesn't pick my changes. 

It seems to cache the first loaded version of db.json. 

When I close and re-open VS Code and start the changes are picked up.

I can't figure out how or why it is being cached.

**Comment by R35007** [comment]
Sorry for the trouble. I will check this and give a fix version as soon as
I can.

**Comment by R35007** [comment]
Hi @kpmccaffrey ,

I have fixed the caching issue. Please install the latest version [v19.0.0](https://marketplace.visualstudio.com/items?itemName=Thinker.mock-server).

**Comment by kpmccaffrey** [comment]
Verified working. Thanks for the quick fix! Great tool!

**Comment by R35007** [comment]
@kpmccaffrey 
I am glad this tool helps you. Please don't forget to give rating and review in vscode marketplace.
Thanks :)
